version: "3"

services:

  postgres:
    image: geocoding/postgres
    build: ./db/init
    container_name: geocoding_postgres
    #image: postgis/postgis
    restart: always
    volumes:
      # dados disponívels em 'var/lib/postgresql/data' estarão disponíveis em './postgres-data'
      - './db/init:/docker-entrypoint-initdb.d/'
      - geocoding_data:/var/lib/postgresql/data
      - ./db/fastspace:/fast/postgresql/data:rw
    #command: [sh, -c, docker, exec, -it, postgres, sh, -c, "psql -U postgres -d gazetteer --command 'refresh materialized view geodata.municipio_mg; refresh materialized view geodata.bairro_bh; refresh materialized view geodata.logradouro_mg;'"]
    env_file:
      - .env

    #["./db/init/start.sh"]
    
  backend:
    image: geocoding/backend
    build: ./init_backend
    container_name: geocoding_backend
    restart: always
    ports:
      - "5003:5003"
    depends_on:
      - postgres
    env_file:
      - .env


  frontend:
    image: geocoding/frontend
    build:
      context: ./web
    environment:
      - REACT_APP_API_URL=http://dev.projetobrumadinho.ufmg.br:5003
    container_name: geocoding_frontend
    volumes:
      - './web/src:/usr/src/app/src'
    ports:
      - '3000:3000'
    depends_on:
      - backend


volumes:
  geocoding_data:
  geocoding_fastspace:
